plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'application'
}

kotlin {
    jvmToolchain(17)
}

application {
    applicationName = 'legado-server'
    mainClass = 'io.legado.server.MainKt'
}

dependencies {
    implementation 'com.google.code.gson:gson:2.13.2'
    implementation 'org.nanohttpd:nanohttpd:2.3.1'
    implementation 'org.nanohttpd:nanohttpd-websocket:2.3.1'
}
