plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'application'
}

kotlin {
    jvmToolchain(21)
}

application {
    applicationName = 'legado-server'
    mainClass = 'io.legado.server.MainKt'
}

dependencies {
    implementation 'com.google.code.gson:gson:2.13.2'
    implementation 'org.jsoup:jsoup:1.21.2'
    implementation 'org.nanohttpd:nanohttpd:2.3.1'
    implementation 'org.nanohttpd:nanohttpd-websocket:2.3.1'
    implementation 'org.graalvm.polyglot:polyglot:24.2.2'
    runtimeOnly 'org.graalvm.polyglot:js:24.2.2'
}
