plugins {
    alias libs.plugins.kotlin.jvm
    id 'application'
}

kotlin {
    jvmToolchain(17)
}

application {
    applicationName = 'legado-server'
    mainClass = 'io.legado.server.MainKt'
}

dependencies {
    implementation(libs.gson)
    implementation(libs.nanohttpd.nanohttpd)
    implementation(libs.nanohttpd.websocket)
}

processResources {
    from("$rootDir/app/src/main/assets/web") {
        into 'web'
    }
    from("$rootDir/app/src/main/assets/defaultData") {
        into 'defaultData'
    }
}
